# config.yaml

# 软件分发平台配置文件

# 管理员账号信息 (用于文件上传)
# !!! 安全提示: 在生产环境中，请考虑使用更安全的秘密管理方式，如环境变量或秘密管理系统。
admin:
  username: your_admin_username # 请替换为你实际的管理员用户名
  password: your_admin_password # 请替换为你实际的管理员密码

# 可以在这里添加其他配置项，例如文件存储路径等 (如果需要的话)
# fileStoragePath: ./uploads 